#!/usr/bin/env python3
"""Analyse CFR adaptive-selector results.

For each (workload, GPU, model) cell, reads the v1 / eb_khat / ada bench
and stats JSONs and reports:
  - TP_MB, TP_EB, TP_ADA  (tokens/s);
  - selector's choice in {MB, EB} and whether it matches the realised
    winner among (v1, eb_khat);
  - the diagnostic Δ(N) (final value from cfr_update_history) and the
    calibration band ε̂ (bootstrap over Δ samples);
  - relative gap (max{TP_EB, TP_MB} − TP_ADA) / max{TP_EB, TP_MB} (%).

Outputs:
  selector_summary.csv
  selector_table.tex
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np


SCEN_ORDER = ("decode_heavy", "balanced", "prefill_heavy", "table4")


def load_pair(wd: Path, sched: str) -> dict | None:
    bench = wd / f"bench_{sched}.json"
    stats = wd / f"{sched}_stats.json"
    if not bench.exists():
        return None
    with open(bench) as f:
        b = json.load(f)
    s = {}
    if stats.exists():
        with open(stats) as f:
            s = json.load(f)
    return {"bench": b, "stats": s}


def selector_decision(stats: dict) -> tuple[str, float, float]:
    """Return (final_choice, final_delta, eps_hat).

    Final choice taken from `mode_switch_history[-1].new_mode` (or the
    cold-start mode if no switch occurred).  Δ(N) is read from the last
    `cfr_update_history` entry.  ε̂ is the std of the recorded Δ samples.
    """
    cfr = stats.get("cfr_update_history") or []
    deltas = [h.get("delta_diagnostic", 0.0) for h in cfr]
    delta_final = deltas[-1] if deltas else 0.0
    eps_hat = float(np.std(deltas)) if len(deltas) >= 2 else 0.0

    msh = stats.get("mode_switch_history") or []
    if msh:
        choice = msh[-1].get("new_mode", "")
    else:
        # If no switches were recorded but auto mode was active, look at the
        # active scheduler at the last stats step.
        steps = stats.get("stats") or []
        choice = ""
        for r in reversed(steps):
            if r.get("active_scheduler"):
                choice = r["active_scheduler"]
                break
    return choice, delta_final, eps_hat


def summarise(wd: Path, scen: str) -> dict | None:
    runs = {sched: load_pair(wd, sched) for sched in ("v1", "eb_khat", "ada")}
    if not all(runs.values()):
        return None

    tp_mb = runs["v1"]["bench"].get("total_token_throughput", 0.0)
    tp_eb = runs["eb_khat"]["bench"].get("total_token_throughput", 0.0)
    tp_ada = runs["ada"]["bench"].get("total_token_throughput", 0.0)

    realised_winner = "EB" if tp_eb >= tp_mb else "MB"
    choice, delta_final, eps_hat = selector_decision(runs["ada"]["stats"])
    # Translate EB+ vocabulary to paper notation.
    sel_label = "EB" if choice == "eb" else ("MB" if choice == "cp" else choice)

    best_pure = max(tp_mb, tp_eb)
    gap_pct = (best_pure - tp_ada) / best_pure * 100 if best_pure > 0 else 0.0
    agreement = "yes" if sel_label == realised_winner else "no"

    return {
        "scenario": scen,
        "tp_mb": tp_mb,
        "tp_eb": tp_eb,
        "tp_ada": tp_ada,
        "realised_winner": realised_winner,
        "selector_choice": sel_label,
        "agreement": agreement,
        "delta_diagnostic": delta_final,
        "eps_hat": eps_hat,
        "delta_in_band": "yes" if abs(delta_final) <= eps_hat else "no",
        "best_pure_tp": best_pure,
        "gap_pct": gap_pct,
    }


def write_csv(rows: list[dict], path: Path) -> None:
    if not rows:
        path.write_text("(empty)\n")
        return
    fields = list(rows[0].keys())
    with open(path, "w") as f:
        f.write(",".join(fields) + "\n")
        for r in rows:
            f.write(",".join(repr(r[k]) if isinstance(r[k], str) else f"{r[k]}"
                              for k in fields) + "\n")


def write_latex(rows: list[dict], path: Path, gpu_tag: str, model: str) -> None:
    rows = sorted(rows, key=lambda r: SCEN_ORDER.index(r["scenario"]))
    with open(path, "w") as f:
        f.write("% Auto-generated by analyze_cfr_selector.py\n")
        f.write(f"% GPU={gpu_tag}, MODEL={model}\n")
        f.write("\\begin{tabular}{lrrrlllrr}\n")
        f.write("\\toprule\n")
        f.write("Workload & TP$_{MB}$ & TP$_{EB}$ & TP$_{ADA}$ "
                "& Choice & Winner & $\\Delta(N)$ & $\\hat\\varepsilon$ "
                "& gap (\\%) \\\\\n")
        f.write("\\midrule\n")
        for r in rows:
            f.write(f"{r['scenario']} & "
                    f"{r['tp_mb']:,.0f} & {r['tp_eb']:,.0f} & {r['tp_ada']:,.0f} & "
                    f"{r['selector_choice']} & {r['realised_winner']} & "
                    f"{r['delta_diagnostic']:.2e} & "
                    f"{r['eps_hat']:.2e} & "
                    f"{r['gap_pct']:.2f} \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("experiment_dir", type=Path)
    args = p.parse_args()
    root = args.experiment_dir
    if not root.is_dir():
        print(f"ERROR: {root} is not a directory", file=sys.stderr)
        return 1

    cfg = json.loads((root / "experiment_config.json").read_text())
    gpu_tag = cfg.get("gpu_tag", "unknown")
    model = cfg.get("model", "unknown")

    rows: list[dict] = []
    for scen in SCEN_ORDER:
        sub = sorted(root.glob(f"{scen}_in*_out*"))
        if not sub:
            continue
        row = summarise(sub[0], scen)
        if row is not None:
            rows.append(row)

    write_csv(rows, root / "selector_summary.csv")
    write_latex(rows, root / "selector_table.tex", gpu_tag, model)
    print(f"Wrote {root / 'selector_summary.csv'}")
    print(f"Wrote {root / 'selector_table.tex'}")
    print()
    if rows:
        print(f"  {'workload':14s} {'TP_MB':>10s} {'TP_EB':>10s} {'TP_ADA':>10s} "
              f"{'choice':>6s} {'win':>5s} {'agree':>6s} "
              f"{'Δ(N)':>10s} {'ε̂':>10s} {'gap%':>6s}")
        for r in rows:
            print(f"  {r['scenario']:14s} "
                  f"{r['tp_mb']:>10,.0f} {r['tp_eb']:>10,.0f} {r['tp_ada']:>10,.0f} "
                  f"{r['selector_choice']:>6s} {r['realised_winner']:>5s} "
                  f"{r['agreement']:>6s} "
                  f"{r['delta_diagnostic']:>10.2e} {r['eps_hat']:>10.2e} "
                  f"{r['gap_pct']:>6.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
