#!/usr/bin/env python3
"""Analyse CFR end-to-end grid-search results.

Reads `outputs/e2e_grid_search/<gpu>_<model>/tb*/bs*/<scenario>/bench_<sched>.json`
and emits:
  - `summary.csv`     : every (sched, scenario, bs, tb) cell with key metrics
  - `optimal_per_scheduler.csv` : best (B, N) per (sched, scenario)
  - `optimal_table.tex`        : LaTeX table for the paper
  - `throughput_<scenario>.png`: TP heatmap by sched (if matplotlib present)

Usage:
    python analyze_cfr_e2e.py <experiment_dir> [--metric total_token_throughput]
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np


def load_bench(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except Exception as exc:  # noqa: BLE001
        print(f"WARN: failed to load {path}: {exc}", file=sys.stderr)
        return None


def harvest_records(root: Path) -> list[dict]:
    records: list[dict] = []
    for tb_dir in sorted(root.glob("tb*")):
        if not tb_dir.is_dir():
            continue
        try:
            tb = int(tb_dir.name[2:])
        except ValueError:
            continue
        for bs_dir in sorted(tb_dir.glob("bs*")):
            if not bs_dir.is_dir():
                continue
            try:
                bs = int(bs_dir.name[2:])
            except ValueError:
                continue
            for scen_dir in sorted(bs_dir.iterdir()):
                if not scen_dir.is_dir():
                    continue
                # scenario_in{L}_out{O}
                scen_name = scen_dir.name.split("_in")[0]
                for bench_file in sorted(scen_dir.glob("bench_*.json")):
                    sched = bench_file.stem.replace("bench_", "")
                    data = load_bench(bench_file)
                    if data is None:
                        continue
                    out_lens = data.get("output_lens") or []
                    in_lens = data.get("input_lens") or []
                    records.append({
                        "scheduler": sched,
                        "scenario": scen_name,
                        "tb": tb,
                        "bs": bs,
                        "completed": data.get("completed", 0),
                        "duration": data.get("duration", 0.0),
                        "request_throughput": data.get("request_throughput", 0.0),
                        "output_throughput": data.get("output_throughput", 0.0),
                        "total_token_throughput": data.get("total_token_throughput", 0.0),
                        "mean_ttft_ms": data.get("mean_ttft_ms", 0.0),
                        "p99_ttft_ms": data.get("p99_ttft_ms", 0.0),
                        "mean_tpot_ms": data.get("mean_tpot_ms", 0.0),
                        "p99_tpot_ms": data.get("p99_tpot_ms", 0.0),
                        "mean_itl_ms": data.get("mean_itl_ms", 0.0),
                        "realised_input_mean": float(np.mean(in_lens)) if in_lens else 0.0,
                        "realised_output_mean": float(np.mean(out_lens)) if out_lens else 0.0,
                        "realised_output_var": float(np.var(out_lens)) if out_lens else 0.0,
                        "result_path": str(bench_file),
                    })
    return records


def write_csv(records: list[dict], path: Path) -> None:
    if not records:
        path.write_text("(empty)\n")
        return
    fields = list(records[0].keys())
    with open(path, "w") as f:
        f.write(",".join(fields) + "\n")
        for r in records:
            f.write(",".join(repr(r[k]) if isinstance(r[k], str) else str(r[k])
                              for k in fields) + "\n")


def best_per_pair(records: list[dict], metric: str) -> list[dict]:
    by_key: dict[tuple[str, str], dict] = {}
    for r in records:
        if r["completed"] == 0:
            continue
        key = (r["scheduler"], r["scenario"])
        if key not in by_key or r[metric] > by_key[key][metric]:
            by_key[key] = r
    return sorted(by_key.values(), key=lambda x: (x["scenario"], x["scheduler"]))


SCEN_LABEL = {
    "decode_heavy":  "Decode-heavy ($\\mu_L{=}128$, $\\mu_O{=}1024$)",
    "balanced":      "Balanced ($\\mu_L{=}\\mu_O{=}512$)",
    "prefill_heavy": "Prefill-heavy ($\\mu_L{=}1024$, $\\mu_O{=}128$)",
}


def write_latex_table(rows: list[dict], path: Path, gpu_tag: str) -> None:
    """Emit a LaTeX tabular for the paper.

    Columns: workload | scheduler | TP (tokens/s) | RPS | mean TTFT | mean TPOT
    Each row is the *best* (B, N) per (sched, scenario) measured by total_token_throughput.
    """
    by_scen: dict[str, list[dict]] = {}
    for r in rows:
        by_scen.setdefault(r["scenario"], []).append(r)

    with open(path, "w") as f:
        f.write("% Auto-generated by analyze_cfr_e2e.py\n")
        f.write(f"% GPU: {gpu_tag}\n")
        f.write("\\begin{tabular}{llrrrr}\n")
        f.write("\\toprule\n")
        f.write("Workload & Scheduler & TP (tok/s) & RPS & TTFT (ms) & TPOT (ms) \\\\\n")
        f.write("\\midrule\n")
        for scen in ("decode_heavy", "balanced", "prefill_heavy"):
            if scen not in by_scen:
                continue
            scen_rows = sorted(by_scen[scen], key=lambda r: r["scheduler"])
            label = SCEN_LABEL.get(scen, scen)
            for i, r in enumerate(scen_rows):
                lab = label if i == 0 else ""
                f.write(f"{lab} & {r['scheduler']} & "
                        f"{r['total_token_throughput']:,.0f} & "
                        f"{r['request_throughput']:.2f} & "
                        f"{r['mean_ttft_ms']:.0f} & "
                        f"{r['mean_tpot_ms']:.1f} \\\\\n")
            f.write("\\midrule\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")


def maybe_plot_heatmaps(records: list[dict], outdir: Path,
                         metric: str, gpu_tag: str) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return
    schedulers = sorted({r["scheduler"] for r in records})
    scenarios = sorted({r["scenario"] for r in records})
    for scen in scenarios:
        bs_vals = sorted({r["bs"] for r in records if r["scenario"] == scen})
        tb_vals = sorted({r["tb"] for r in records if r["scenario"] == scen})
        if not bs_vals or not tb_vals:
            continue
        fig, axes = plt.subplots(
            1, len(schedulers), figsize=(4 * len(schedulers), 3.5),
            squeeze=False)
        for ax, sched in zip(axes[0], schedulers):
            grid = np.full((len(bs_vals), len(tb_vals)), np.nan)
            for r in records:
                if r["scheduler"] != sched or r["scenario"] != scen:
                    continue
                if r["completed"] == 0:
                    continue
                i = bs_vals.index(r["bs"])
                j = tb_vals.index(r["tb"])
                grid[i, j] = r[metric]
            im = ax.imshow(grid, aspect="auto", origin="lower", cmap="viridis")
            ax.set_xticks(range(len(tb_vals)))
            ax.set_xticklabels(tb_vals, rotation=45)
            ax.set_yticks(range(len(bs_vals)))
            ax.set_yticklabels(bs_vals)
            ax.set_xlabel("token budget")
            ax.set_ylabel("max-num-seqs")
            ax.set_title(f"{sched} — {scen}")
            fig.colorbar(im, ax=ax)
        fig.suptitle(f"{gpu_tag}: {metric}")
        fig.tight_layout()
        out = outdir / f"heatmap_{scen}_{metric}.png"
        fig.savefig(out, dpi=120)
        plt.close(fig)
        print(f"  wrote {out}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("experiment_dir", type=Path)
    p.add_argument("--metric", default="total_token_throughput",
                    help="metric to optimise over (B, N) for the optimal table")
    args = p.parse_args()

    root = args.experiment_dir
    if not root.is_dir():
        print(f"ERROR: {root} is not a directory", file=sys.stderr)
        return 1

    cfg_file = root / "experiment_config.json"
    cfg = json.loads(cfg_file.read_text()) if cfg_file.exists() else {}
    gpu_tag = cfg.get("gpu_tag", "unknown")

    records = harvest_records(root)
    print(f"Loaded {len(records)} records from {root}")

    write_csv(records, root / "summary.csv")
    print(f"  wrote {root / 'summary.csv'}")

    optimal = best_per_pair(records, args.metric)
    write_csv(optimal, root / "optimal_per_scheduler.csv")
    print(f"  wrote {root / 'optimal_per_scheduler.csv'}")

    write_latex_table(optimal, root / "optimal_table.tex", gpu_tag)
    print(f"  wrote {root / 'optimal_table.tex'}")

    print("\nOptimal-(B, N) summary (best by", args.metric, "):")
    print(f"  {'scenario':14s} {'sched':10s} {'tb':>6s} {'bs':>5s} "
          f"{'TP (tok/s)':>12s} {'RPS':>7s} {'TTFT (ms)':>10s} {'TPOT (ms)':>10s}")
    for r in optimal:
        print(f"  {r['scenario']:14s} {r['scheduler']:10s} "
              f"{r['tb']:>6d} {r['bs']:>5d} "
              f"{r['total_token_throughput']:>12,.0f} "
              f"{r['request_throughput']:>7.2f} "
              f"{r['mean_ttft_ms']:>10.0f} "
              f"{r['mean_tpot_ms']:>10.1f}")

    maybe_plot_heatmaps(records, root, args.metric, gpu_tag)
    return 0


if __name__ == "__main__":
    sys.exit(main())
